/**
 * WP-2.2 — typed event registry: shared types (HISTORY_EVENT_CATALOG §1/§4/§5).
 *
 * The event surface is the frozen contract:
 *  - envelope shape: HISTORY_EVENT_CATALOG §1 (L14-27) +
 *    `schema/history/history-event-envelope.schema.json`;
 *  - the 20-event discriminated union: `schema/history/history-events.schema.json`
 *    (one `oneOf` branch per event; the EVENT TYPE SET is schema-driven — see
 *    registry.ts);
 *  - shared structures (ActorRef / SourceRef / TypedRef / id patterns):
 *    `schema/common.schema.json`;
 *  - emitter matrix (U/A/P), mutation flag (M), owner rule, categories:
 *    HISTORY_EVENT_CATALOG §4 总表;
 *  - per-event payload tables: HISTORY_EVENT_CATALOG §5;
 *  - invariants: ARCHITECTURE.md §5.3 INV-HIST-1..9, INV-TASK-1/3.
 *
 * Layer rules (WP-2.2 boundary): this module is PURE validation + registration
 * metadata — it never rewrites events (no replay, WP-2.3), never writes SQLite
 * (append belongs to the store layer, WP-2.1 schema) and never imports
 * persistence. Every byte of frozen schema JSON flows in through the injected
 * `HistorySchemaReader` (loader pattern, cf. WP-1.1 `ResearchFileReader`);
 * the kernel itself performs no I/O. No DSH imports (INV-PERM-5).
 *
 * NOTE (frozen-contract spelling, see WP-2.2 report): the machine-readable
 * truth `schema/history/history-events.schema.json` names event #8
 * `ACCEPTANCE_CRITERIA_CHANGED`; the semantic document
 * HISTORY_EVENT_CATALOG §4/§5 spells it `ACCEPTANCE_CRITERION_CHANGED`. The
 * registry is schema-driven, so the schema spelling is the canonical
 * eventType here.
 */

/* ------------------------------------------------------------------ *
 * Shared structures (mirrors of schema/common.schema.json $defs)
 * ------------------------------------------------------------------ */

/** The 24 object kinds (common.schema.json `objectKind`). */
export type ObjectKind =
  | 'PROJECT'
  | 'TOPIC'
  | 'WORKSTREAM'
  | 'TASK'
  | 'GATE'
  | 'MILESTONE'
  | 'RUN'
  | 'CLAIM'
  | 'FACT'
  | 'ARTIFACT'
  | 'RELATION'
  | 'OBJECTIVE'
  | 'INTERVENTION'
  | 'NEXT_ACTION'
  | 'BLOCKER'
  | 'INTERACTION'
  | 'REPORTING_ITEM'
  | 'SCHEDULED_EVENT'
  | 'INBOX_ITEM'
  | 'PLAN_FORK'
  | 'TOPOLOGY_EDGE'
  | 'DISCOVERED_SESSION'
  | 'HISTORY_EVENT'
  | 'ANALYSIS_RECORD'

/** One `{kind, id}` reference (common.schema.json `typedRef`). */
export interface TypedRef {
  kind: ObjectKind
  id: string
}

/** `actorRef` (common.schema.json; HISTORY_EVENT_CATALOG §1 「谁做的」). */
export interface ActorRef {
  kind: 'USER' | 'AGENT' | 'PLUGIN' | 'SYSTEM'
  user_id?: string
  /** R id; AGENT-emitted events must reference an existing Run (catalog §5). */
  run_id?: string
  session_id?: string
  label?: string
}

/** `sourceRef` (common.schema.json; envelope `source?` 「从哪来的」). */
export interface SourceRef {
  kind: 'DSH_SESSION' | 'FILE' | 'GIT' | 'MANUAL' | 'IMPORT' | 'INTERACTION' | 'PLUGIN'
  session_id?: string
  path?: string
  commit_oid?: string
  interaction_id?: string
  note?: string
}

/* ------------------------------------------------------------------ *
 * Event envelope (HISTORY_EVENT_CATALOG §1)
 * ------------------------------------------------------------------ */

/**
 * The 9-field envelope. `eventType` stays `string` at the envelope level
 * (the schema discriminator is `const` per branch); `EventOf<T>` narrows it.
 * Time fields are epoch ms (memory carrier, DOMAIN_SCHEMA §1.2).
 */
export interface HistoryEventEnvelope<P = unknown> {
  /** H id; unique within the Project, monotonically allocated (§1). */
  eventId: string
  /** The single owner workstream (INV-HIST-3). */
  ownerWorkstreamId: string
  /** Owner-workstream-local sequence, 1..N, assigned at append, never rewritten (INV-HIST-6). */
  eventSeq: number
  /** §4 catalog event type name. */
  eventType: string
  /** Payload schema version; all V1 = 1 (INV-HIST-4). */
  schemaVersion: number
  /** When the real research event happened (epoch ms). Late registration may be older than existing events (§1/§2). */
  occurredAt: number
  /** When the plugin recorded the event (epoch ms); generated by the plugin, never caller-specified (§1). */
  recordedAt: number
  /** Who did it. */
  actor: ActorRef
  /** Where it came from (optional). */
  source?: SourceRef
  /** Strongly typed by (eventType, schemaVersion). */
  payload: P
}

/* ------------------------------------------------------------------ *
 * Payload types (one per event; field tables from HISTORY_EVENT_CATALOG §5,
 * shapes frozen in schema/history/history-events.schema.json)
 * ------------------------------------------------------------------ */

/** Task execution state (DOMAIN_SCHEMA §13; history-events.schema.json `taskExecution`). */
export type TaskExecution = 'PLANNED' | 'ACTIVE' | 'PAUSED' | 'EXECUTED' | 'CANCELLED'
/** Task validation state (DOMAIN_SCHEMA §13). */
export type TaskValidation = 'NOT_REQUIRED' | 'PENDING' | 'UNDER_REVIEW' | 'PASSED' | 'FAILED'
/** Run status (DOMAIN_SCHEMA §13: RUNNING → FINISHED|FAILED|CANCELLED, terminal). */
export type RunStatus = 'RUNNING' | 'FINISHED' | 'FAILED' | 'CANCELLED'
/** Claim status (DOMAIN_SCHEMA §13: ACTIVE → RETRACTED, terminal). */
export type ClaimStatus = 'ACTIVE' | 'RETRACTED'
/** Artifact status (DOMAIN_SCHEMA §13: REGISTERED ↔ MISSING). */
export type ArtifactStatus = 'REGISTERED' | 'MISSING'
/** Relation status (DOMAIN_SCHEMA §8 derived field). */
export type RelationStatus = 'ACTIVE' | 'REMOVED'
/** Gate evaluation result (HISTORY_EVENT_CATALOG §5.6). */
export type GateResult = 'PASSED' | 'FAILED' | 'WAIVED'
/** Milestone derived state (DOMAIN_SCHEMA §13). */
export type MilestoneStatus = 'PLANNED' | 'ACHIEVED' | 'DROPPED'
/** Workstream / topology-edge lifecycle (DOMAIN_SCHEMA §13). */
export type WsLifecycle = 'PLANNED' | 'REALIZED' | 'DROPPED'
/** TopologyEdge operation (DOMAIN_SCHEMA §3.1). */
export type EdgeOperation = 'FORK' | 'MERGE'
/** Intervention origin (HISTORY_EVENT_CATALOG §5.7). */
export type InterventionOrigin = 'USER' | 'AGENT_REPORT' | 'AUTO_FLOODING' | 'AUTO_AUDIT'
/** The 10 V1 relation types (DOMAIN_SCHEMA §8; history-events.schema.json `relationType`). */
export type RelationType =
  | 'DEPENDS_ON'
  | 'SUPPORTED_BY'
  | 'CONTRADICTED_BY'
  | 'DERIVED_FROM'
  | 'PRODUCED_BY'
  | 'VALIDATED_BY'
  | 'CONSUMES'
  | 'CONTRIBUTES_TO'
  | 'IMPLEMENTS'
  | 'RELATED_TO'
/** ArtifactType (common.schema.json). */
export type ArtifactType = 'DATASET' | 'FIGURE' | 'MODEL' | 'CODE' | 'REPORT' | 'NOTE' | 'OTHER'

/* ------------------------------------------------------------------ *
 * Payload interfaces (§5 field tables; snake_case = frozen schema keys)
 * ------------------------------------------------------------------ */

/** §5.1 RUN_STARTED — 「一个 Run 开始」. */
export interface RunStartedPayload {
  /** R id; must be NEW (does not exist). */
  run_id: string
  /** T id; optional; must exist and belong to the owner WS. */
  task_id?: string
  dsh_session_id?: string
  intent?: string
  /** Who initiated the run. */
  initiated_by: ActorRef
}

/** One entry of a batch launch (§5.2 `runs[]`). */
export interface RunStartEntry {
  /** R id; must be NEW. */
  run_id: string
  task_id?: string
  dsh_session_id?: string
  intent?: string
}

/** §5.2 RUNS_STARTED — 「一次 batch launch 启动多个 Run」(sole INV-HIST-2 exception). */
export interface RunsStartedPayload {
  /** ≥2 entries (=1 ⇒ use RUN_STARTED; schema `minItems: 2`). */
  runs: RunStartEntry[]
  batch_source?: SourceRef
}

/** §5.1 RUN_FINISHED — run must be RUNNING. */
export interface RunFinishedPayload {
  run_id: string
  outcome_summary?: string
}

/** §5.1 RUN_FAILED — run must be RUNNING. */
export interface RunFailedPayload {
  run_id: string
  error_summary?: string
  /** Free label, e.g. `OOM` / `DATA_MISSING`. */
  failure_kind?: string
}

/** §5.1 RUN_CANCELLED — run must be RUNNING. */
export interface RunCancelledPayload {
  run_id: string
  reason?: string
  cancelled_by: ActorRef
}

/** §5.2 TASK_EXECUTION_CHANGED — mutation; from must equal current derived execution (INV-HIST-5). */
export interface TaskExecutionChangedPayload {
  /** T id; exists and belongs to the owner WS. */
  task_id: string
  from: TaskExecution
  to: TaskExecution
  reason?: string
}

/** §5.2 TASK_VALIDATION_CHANGED — mutation; from must equal current derived validation (INV-HIST-5). */
export interface TaskValidationChangedPayload {
  task_id: string
  from: TaskValidation
  to: TaskValidation
  reviewer?: ActorRef
  note?: string
}

/** §5.2 ACCEPTANCE_CRITERIA_CHANGED — mutation; `from`/`to` are AC text snapshots (semantic audit). */
export interface AcceptanceCriteriaChangedPayload {
  task_id: string
  from: string[]
  to: string[]
}

/** §5.3 FACT_RECORDED — fact must be NEW. */
export interface FactRecordedPayload {
  /** F id; must be NEW. */
  fact_id: string
  /** Non-empty (schema `minLength: 1`). */
  statement: string
  /** Required when the event is AGENT-emitted (§5.3). */
  created_by_run?: string
  references?: string[]
}

/** §5.3 CLAIM_RECORDED — claim must be NEW. */
export interface ClaimRecordedPayload {
  /** C id; must be NEW. */
  claim_id: string
  statement: string
  /** Required when the event is AGENT-emitted (§5.3). */
  created_by_run?: string
  references?: string[]
}

/** §5.3 CLAIM_RETRACTED — claim must be ACTIVE. */
export interface ClaimRetractedPayload {
  claim_id: string
  reason?: string
}

/** §5.4 ARTIFACT_REGISTERED — artifact must be NEW. */
export interface ArtifactRegisteredPayload {
  /** A id; must be NEW. */
  artifact_id: string
  type: ArtifactType
  title: string
  uri: string
  content_hash?: string
  created_by_run?: string
  /** T id; optional; must belong to the owner WS. */
  related_task?: string
  /** A id; optional; must exist. */
  supersedes?: string
}

/** §5.4 ARTIFACT_MARKED_MISSING — artifact must be REGISTERED. */
export interface ArtifactMarkedMissingPayload {
  artifact_id: string
  reason?: string
  /** P-emitted: the audit source. */
  detected_by?: ActorRef
}

/** §5.5 RELATION_ADDED — relation must be NEW. */
export interface RelationAddedPayload {
  /** REL id; must be NEW. */
  relation_id: string
  source: TypedRef
  relation_type: RelationType
  target: TypedRef
}

/** §5.5 RELATION_REMOVED — relation must be ACTIVE; endpoints redundantly recorded for audit replay. */
export interface RelationRemovedPayload {
  relation_id: string
  source: TypedRef
  relation_type: RelationType
  target: TypedRef
  reason?: string
}

/** §5.6 GATE_EVALUATED — repeatable; gate current state = last evaluation result. */
export interface GateEvaluatedPayload {
  /** G id; exists and belongs to the owner WS. */
  gate_id: string
  result: GateResult
  /** `WAIVED` only for actor.kind=USER with a non-empty `note` (§5.6). */
  evaluated_by: ActorRef
  note?: string
  /** Evaluation evidence (Fact/Artifact, …). */
  evidence_refs?: TypedRef[]
}

/** §5.6 MILESTONE_ACHIEVED — milestone must be PLANNED; ACHIEVED is terminal. */
export interface MilestoneAchievedPayload {
  milestone_id: string
  evidence_refs?: TypedRef[]
  note?: string
}

/** §5.7 INTERVENTION_CREATED — intervention must be NEW; owner = first related WS. */
export interface InterventionCreatedPayload {
  /** IV id; must be NEW. */
  intervention_id: string
  title: string
  /** `AUTO_*` origins require actor.kind=PLUGIN (§5.7). */
  origin: InterventionOrigin
  /** Workstream association is derived from these refs (no refs ⇒ no event). */
  source_refs?: TypedRef[]
}

/** §5.8 TOPOLOGY_FORK_REALIZED — edge must be PLANNED; owner = inputs[0] (INV-HIST-9). */
export interface TopologyForkRealizedPayload {
  /** TE id; exists, PLANNED, same owner Topic. */
  topology_edge_id: string
  /** V1: exactly 1 (schema `maxItems: 1`); mirrors the edge's declared inputs. */
  inputs: string[]
  /** ≥1 unique; mirrors the edge's declared outputs. */
  outputs: string[]
}

/** §5.8 TOPOLOGY_MERGE_REALIZED — edge must be PLANNED; owner = outputs[0] (INV-HIST-9). */
export interface TopologyMergeRealizedPayload {
  topology_edge_id: string
  /** ≥1 unique; mirrors the edge's declared inputs. */
  inputs: string[]
  /** V1: exactly 1 (schema `maxItems: 1`). */
  outputs: string[]
}

/* ------------------------------------------------------------------ *
 * The 20-event discriminated union (type surface)
 * ------------------------------------------------------------------ */

/** eventType → payload type (the 20 rows of the §4 总表, schema-driven set). */
export interface HistoryEventMap {
  RUN_STARTED: RunStartedPayload
  RUNS_STARTED: RunsStartedPayload
  RUN_FINISHED: RunFinishedPayload
  RUN_FAILED: RunFailedPayload
  RUN_CANCELLED: RunCancelledPayload
  TASK_EXECUTION_CHANGED: TaskExecutionChangedPayload
  TASK_VALIDATION_CHANGED: TaskValidationChangedPayload
  /** Schema spelling (machine truth); the catalog spells it `ACCEPTANCE_CRITERION_CHANGED`. */
  ACCEPTANCE_CRITERIA_CHANGED: AcceptanceCriteriaChangedPayload
  FACT_RECORDED: FactRecordedPayload
  CLAIM_RECORDED: ClaimRecordedPayload
  CLAIM_RETRACTED: ClaimRetractedPayload
  ARTIFACT_REGISTERED: ArtifactRegisteredPayload
  ARTIFACT_MARKED_MISSING: ArtifactMarkedMissingPayload
  RELATION_ADDED: RelationAddedPayload
  RELATION_REMOVED: RelationRemovedPayload
  GATE_EVALUATED: GateEvaluatedPayload
  MILESTONE_ACHIEVED: MilestoneAchievedPayload
  INTERVENTION_CREATED: InterventionCreatedPayload
  TOPOLOGY_FORK_REALIZED: TopologyForkRealizedPayload
  TOPOLOGY_MERGE_REALIZED: TopologyMergeRealizedPayload
}

/** The 20 registered event type names. */
export type HistoryEventType = keyof HistoryEventMap

/**
 * The event with a narrowed `eventType` and the matching payload. Built as a
 * homomorphic mapped type (NOT an intersection) so the union is a CLASSIC
 * discriminated union: `switch (event.eventType)` narrows `event.payload` in
 * every member (validate.ts relies on this).
 */
export type EventOf<T extends HistoryEventType> = {
  [K in keyof HistoryEventEnvelope<HistoryEventMap[T]>]: K extends 'eventType'
    ? T
    : HistoryEventEnvelope<HistoryEventMap[T]>[K]
}

/** The full discriminated union (discriminant: `eventType`). Mapped over the
 *  20 type names so each member is its own object type — `switch` narrows. */
export type HistoryEvent = { [T in HistoryEventType]: EventOf<T> }[HistoryEventType]

/** Plain (non-narrowing) equality checker for the discriminant. For NARROWING
 *  use the concrete guards below (a generic type predicate `event is EventOf<T>`
 *  is not expressible: for generic `T`, `EventOf<T>` is not a provable member
 *  of the distributed `HistoryEvent` union). */
export function isEventOf<T extends HistoryEventType>(type: T, event: HistoryEvent): boolean {
  return event.eventType === type
}

/**
 * Type guards, one per event type (usage: `if (isRunStarted(e)) e.payload.run_id`).
 * Each predicate is written against the CONCRETE literal: `EventOf<literal>`
 * IS a member of the distributed `HistoryEvent` union, so the narrowing is
 * sound and the 20 guards are total over the catalog.
 */
export const isRunStarted: (event: HistoryEvent) => event is EventOf<'RUN_STARTED'> = (event) => event.eventType === 'RUN_STARTED'
export const isRunsStarted: (event: HistoryEvent) => event is EventOf<'RUNS_STARTED'> = (event) => event.eventType === 'RUNS_STARTED'
export const isRunFinished: (event: HistoryEvent) => event is EventOf<'RUN_FINISHED'> = (event) => event.eventType === 'RUN_FINISHED'
export const isRunFailed: (event: HistoryEvent) => event is EventOf<'RUN_FAILED'> = (event) => event.eventType === 'RUN_FAILED'
export const isRunCancelled: (event: HistoryEvent) => event is EventOf<'RUN_CANCELLED'> = (event) => event.eventType === 'RUN_CANCELLED'
export const isTaskExecutionChanged: (event: HistoryEvent) => event is EventOf<'TASK_EXECUTION_CHANGED'> = (event) => event.eventType === 'TASK_EXECUTION_CHANGED'
export const isTaskValidationChanged: (event: HistoryEvent) => event is EventOf<'TASK_VALIDATION_CHANGED'> = (event) => event.eventType === 'TASK_VALIDATION_CHANGED'
export const isAcceptanceCriteriaChanged: (event: HistoryEvent) => event is EventOf<'ACCEPTANCE_CRITERIA_CHANGED'> = (event) => event.eventType === 'ACCEPTANCE_CRITERIA_CHANGED'
export const isFactRecorded: (event: HistoryEvent) => event is EventOf<'FACT_RECORDED'> = (event) => event.eventType === 'FACT_RECORDED'
export const isClaimRecorded: (event: HistoryEvent) => event is EventOf<'CLAIM_RECORDED'> = (event) => event.eventType === 'CLAIM_RECORDED'
export const isClaimRetracted: (event: HistoryEvent) => event is EventOf<'CLAIM_RETRACTED'> = (event) => event.eventType === 'CLAIM_RETRACTED'
export const isArtifactRegistered: (event: HistoryEvent) => event is EventOf<'ARTIFACT_REGISTERED'> = (event) => event.eventType === 'ARTIFACT_REGISTERED'
export const isArtifactMarkedMissing: (event: HistoryEvent) => event is EventOf<'ARTIFACT_MARKED_MISSING'> = (event) => event.eventType === 'ARTIFACT_MARKED_MISSING'
export const isRelationAdded: (event: HistoryEvent) => event is EventOf<'RELATION_ADDED'> = (event) => event.eventType === 'RELATION_ADDED'
export const isRelationRemoved: (event: HistoryEvent) => event is EventOf<'RELATION_REMOVED'> = (event) => event.eventType === 'RELATION_REMOVED'
export const isGateEvaluated: (event: HistoryEvent) => event is EventOf<'GATE_EVALUATED'> = (event) => event.eventType === 'GATE_EVALUATED'
export const isMilestoneAchieved: (event: HistoryEvent) => event is EventOf<'MILESTONE_ACHIEVED'> = (event) => event.eventType === 'MILESTONE_ACHIEVED'
export const isInterventionCreated: (event: HistoryEvent) => event is EventOf<'INTERVENTION_CREATED'> = (event) => event.eventType === 'INTERVENTION_CREATED'
export const isTopologyForkRealized: (event: HistoryEvent) => event is EventOf<'TOPOLOGY_FORK_REALIZED'> = (event) => event.eventType === 'TOPOLOGY_FORK_REALIZED'
export const isTopologyMergeRealized: (event: HistoryEvent) => event is EventOf<'TOPOLOGY_MERGE_REALIZED'> = (event) => event.eventType === 'TOPOLOGY_MERGE_REALIZED'

/* ------------------------------------------------------------------ *
 * Validation context (the operational state snapshot, injected)
 *
 * The validator is a PURE function over (registry, event, ctx): ctx is a
 * read-only snapshot of the derived state the event would mutate. Absence
 * from a map = the object does not exist (the store assembles a complete
 * snapshot before calling). 「且不产生副作用」 (TC-HIST-001) follows from the
 * calling convention: validateEvent never writes — no map mutation, no I/O,
 * no event emission.
 * ------------------------------------------------------------------ */

export interface WorkstreamSnapshot {
  readonly topicId: string
  readonly lifecycle: WsLifecycle
}
export interface TaskSnapshot {
  readonly workstreamId: string
  readonly execution: TaskExecution
  readonly validation: TaskValidation
  /** AC text snapshot (empty ⇒ validation can only be NOT_REQUIRED, INV-TASK-3). */
  readonly acceptanceCriteria: readonly string[]
}
export interface RunSnapshot {
  readonly workstreamId: string
  readonly status: RunStatus
}
export interface ClaimSnapshot {
  readonly workstreamId: string
  readonly status: ClaimStatus
}
export interface FactSnapshot {
  readonly workstreamId: string
}
export interface ArtifactSnapshot {
  readonly workstreamId: string
  readonly status: ArtifactStatus
}
export interface RelationSnapshot {
  readonly status: RelationStatus
  readonly source: TypedRef
  readonly relationType: RelationType
  readonly target: TypedRef
}
export interface GateSnapshot {
  readonly workstreamId: string
  /** Last evaluation result; `null` = no evaluation yet (state PLANNED, §5.6). */
  readonly lastResult: GateResult | null
}
export interface MilestoneSnapshot {
  readonly workstreamId: string
  readonly status: MilestoneStatus
}
export interface InterventionSnapshot {
  readonly workstreamIds: readonly string[]
}
export interface TopologyEdgeSnapshot {
  readonly topicId: string
  readonly operation: EdgeOperation
  readonly lifecycle: WsLifecycle
  readonly inputs: readonly string[]
  readonly outputs: readonly string[]
}

/** Read-only snapshot of the operational (SQLite-side) state for validation. */
export interface HistoryObjectContext {
  readonly workstreams: ReadonlyMap<string, WorkstreamSnapshot>
  readonly tasks: ReadonlyMap<string, TaskSnapshot>
  readonly runs: ReadonlyMap<string, RunSnapshot>
  readonly claims: ReadonlyMap<string, ClaimSnapshot>
  readonly facts: ReadonlyMap<string, FactSnapshot>
  readonly artifacts: ReadonlyMap<string, ArtifactSnapshot>
  readonly relations: ReadonlyMap<string, RelationSnapshot>
  readonly gates: ReadonlyMap<string, GateSnapshot>
  readonly milestones: ReadonlyMap<string, MilestoneSnapshot>
  readonly interventions: ReadonlyMap<string, InterventionSnapshot>
  readonly topologyEdges: ReadonlyMap<string, TopologyEdgeSnapshot>
}

/* ------------------------------------------------------------------ *
 * Structured rejection (precise code + path + message, TC-DOM-027 style)
 * ------------------------------------------------------------------ */

export type EventRejectCode =
  /** Registry failed to load (see HistoryEventRegistry.loadErrors); nothing can be validated. */
  | 'REGISTRY_UNUSABLE'
  /** Envelope field violation (§1) incl. unknown (eventType, schemaVersion) or payload schema failure (INV-HIST-4). */
  | 'ENVELOPE'
  /** actor.kind is not in the event's emitter matrix (catalog §3.6 / §4 E column). */
  | 'EMITTER_FORBIDDEN'
  /** Declared `from` ≠ object's current derived state (INV-HIST-5; TC-HIST-001). */
  | 'FROM_MISMATCH'
  /** Object exists but its current state is not the event's implicit `from` state. */
  | 'WRONG_STATE'
  /** (from, to) not in the §13 legal transition table (INV-TASK-1). */
  | 'ILLEGAL_TRANSITION'
  /** A referenced object does not exist (catalog §5 「payload 内引用的对象存在」). */
  | 'OBJECT_NOT_FOUND'
  /** A "新建" (fresh) id already exists (catalog §5 「新建」). */
  | 'OBJECT_ALREADY_EXISTS'
  /** Owner-workstream rule violation (§4 owner column / INV-HIST-3 / INV-HIST-9). */
  | 'OWNER_MISMATCH'
  /** Payload-internal cross-field rule (WAIVED⇒USER+note, NOT_REQUIRED⇒AC empty, AGENT⇒run_id/created_by_run, relation 组合表, redundancy, payload-vs-edge mirror). */
  | 'CROSS_FIELD'

/** One precisely-located validation error. */
export interface EventValidationError {
  readonly code: EventRejectCode
  /** JSON-pointer path within the event (`/payload/from`, `/actor/kind`); undefined = event-level. */
  readonly path?: string
  readonly message: string
}

/** Structured outcome of `validateEvent` (pure: no write ever occurs). */
export type EventValidationResult =
  | { readonly ok: true; readonly eventType: HistoryEventType; readonly ownerWorkstreamId: string }
  | { readonly ok: false; readonly errors: readonly EventValidationError[] }

/* ------------------------------------------------------------------ *
 * Registry entry (schema-driven type set × §4/§5 static metadata)
 * ------------------------------------------------------------------ */

/** §4 总表 类别 column. */
export type EventCategory =
  | 'Run'
  | 'Task'
  | 'SemanticTag'
  | 'Artifact'
  | 'Relation'
  | 'GateMilestone'
  | 'HumanAttention'
  | 'Topology'

/** The three emitters of the §4 E column (U/A/P). */
export type EmitterKind = 'USER' | 'AGENT' | 'PLUGIN'

/** §4 总表 「owner workstream」 column (per-event rule). */
export type OwnerRule =
  /** Default: the subject object's own workstream. */
  | { readonly kind: 'objectWs' }
  /** RUNS_STARTED: one same-payload event per relevant owner WS (store fans out; §5.2 信封特例). */
  | { readonly kind: 'perOwnerBatch' }
  /** Relation events: `source.workstream ?? target.workstream` (§4/§8; both non-local ⇒ reject). */
  | { readonly kind: 'relationEndpoints' }
  /** Intervention: first related WS derivable from source_refs; none ⇒ no event (§5.7). */
  | { readonly kind: 'firstRelatedWs' }
  /** TOPOLOGY_FORK_REALIZED: `inputs[0]` (source WS, INV-HIST-9). */
  | { readonly kind: 'topologyInputs0' }
  /** TOPOLOGY_MERGE_REALIZED: `outputs[0]` (resulting WS, INV-HIST-9). */
  | { readonly kind: 'topologyOutputs0' }

/**
 * The §13 state machines an event may transition (plus `acSnapshot` for
 * ACCEPTANCE_CRITERIA_CHANGED — a text-snapshot change with from-equality but
 * no state machine).
 */
export type StateMachine =
  | 'taskExecution'
  | 'taskValidation'
  | 'run'
  | 'claim'
  | 'artifact'
  | 'milestone'
  | 'gate'
  | 'relation'
  | 'topologyEdge'
  | 'acSnapshot'

/** The from→to semantics of one event (the 迁移行 of its §5 详细规范). */
export interface EventTransition {
  readonly machine: StateMachine
  /** `payload`: from/to are read from the payload (mutation events, M column ●).
   *  `implicit`: the event declares its `from` implicitly (e.g. RUN_FINISHED requires RUNNING). */
  readonly fromSource: 'payload' | 'implicit'
  /** fromSource=`implicit`: the object's current state must be one of these. */
  readonly expectedFrom?: readonly string[]
}

/**
 * Aggregate (wrapper) semantics — §3.1 atomicity exception + §5.2 batch
 * envelope + §3.7 readability aggregation (INV-HIST-2/8, TC-HIST-007).
 * RUNS_STARTED is the ONLY aggregate event in the V1 catalog.
 */
export interface AggregateRules {
  readonly eventType: 'RUNS_STARTED'
  readonly memberField: 'runs'
  /** schema `minItems: 2` — a single-run launch must use RUN_STARTED. */
  readonly minMembers: 2
  /** §5.2 信封特例: one same-payload event per relevant owner WS. */
  readonly perOwnerEnvelope: true
  /** Run end is always recorded per Run (RUN_FINISHED/FAILED/CANCELLED; no RUNS_FINISHED). */
  readonly runEndsPerRun: true
}

/** One row of the typed registry (20 rows total). */
export interface EventRegistryEntry {
  readonly eventType: HistoryEventType
  /** Payload schema version from the schema branch const (V1: all 1). */
  readonly schemaVersion: number
  readonly category: EventCategory
  /** §4 M column (● = mutation: payload must carry from→to, INV-HIST-5). */
  readonly isMutation: boolean
  /** §4 E column (U/A/P). */
  readonly emitters: readonly EmitterKind[]
  readonly ownerRule: OwnerRule
  /** Present when the event moves a state machine (or a snapshot). */
  readonly transition?: EventTransition
  /** Present only for the aggregate event. */
  readonly aggregate?: AggregateRules
  /** §4 总表 一句话语义. */
  readonly semantics: string
}

/* ------------------------------------------------------------------ *
 * Registry loading (schemaDir injection, loader pattern)
 * ------------------------------------------------------------------ */

/**
 * Read-only schema access (cf. WP-1.1 `ResearchFileReader`, minus `readDir`
 * — the registry reads exactly two files). `readFile` returns `null` for a
 * missing/non-regular path and throws on I/O failure.
 */
export interface HistorySchemaReader {
  readonly readFile: (path: string) => string | null
}

export type HistoryRegistryErrorCode =
  /** A schema file is missing, unreadable, or not valid JSON. */
  | 'SCHEMA_LOAD'
  /** A per-event validator failed to compile. */
  | 'SCHEMA_COMPILE'
  /** The schema's oneOf type set and the §4/§5 metadata disagree (frozen-contract sync check, catalog §7.2). */
  | 'CATALOG_SYNC'

export interface HistoryRegistryLoadError {
  readonly code: HistoryRegistryErrorCode
  readonly file?: string
  readonly message: string
}

/** Outcome of the envelope + payload shape check (§1 + INV-HIST-4, precise AJV errors). */
export type ShapeCheck =
  | { readonly ok: true; readonly eventType: HistoryEventType }
  | { readonly ok: false; readonly errors: readonly EventValidationError[] }

/** The loaded typed event registry (20 events, schema-driven). */
export interface HistoryEventRegistry {
  /** The schemaDir the registry was loaded from. */
  readonly schemaDir: string
  /** False when loadErrors is non-empty; checkShape then reports REGISTRY_UNUSABLE. */
  readonly isUsable: boolean
  readonly loadErrors: readonly HistoryRegistryLoadError[]
  /** All registered event types (schema oneOf order). */
  readonly eventTypes: readonly HistoryEventType[]
  /** eventType → registry entry. */
  readonly events: ReadonlyMap<HistoryEventType, EventRegistryEntry>
  /** Envelope (§1) + payload-discrimination shape check for one candidate event. */
  readonly checkShape: (event: unknown) => ShapeCheck
}
