/**
 * WP-2.1 — operational SQLite store: public type surface.
 *
 * The store is the persistence face of the operational 真源
 * (`$DSH_HOME/research-control/<project-id>/research.sqlite`,
 * DOMAIN_SCHEMA §15 / ARCHITECTURE §4). It wraps `node:sqlite`
 * `DatabaseSync` (DSH_ADAPTER §9) and owns:
 *   - the `history_event` table (§15 L614: PK `event_id`,
 *     `UNIQUE(owner_workstream_id, event_seq)`, indexes
 *     `(owner_workstream_id, occurred_at, event_seq)`,
 *     `(event_type, occurred_at)`, `(recorded_at)`);
 *   - the `derived_state` table (§15 L627: PK `(object_kind, object_id)`,
 *     `state` JSON replaced wholesale, written in the SAME transaction as
 *     the event append);
 *   - the `meta` table (§15 L628: `key` PK; ID counters, DB schema version)
 *     exposed as the WP-1.6 reserved `MetaStore` sqlite backend.
 *
 * Boundary (WP-2.1): NO replay/query projections (WP-2.3); NO event
 * validation (WP-2.2 injects the validation callback through
 * `AppendEventsOptions.validate`); NO delete/update API — the event log is
 * append-only by construction (INV-HIST-1), enforced at this type surface
 * (no such method exists) AND at the storage level (triggers in
 * schema.ts reject raw UPDATE/DELETE on `history_event`).
 *
 * Time representation (DOMAIN_SCHEMA §1.2): epoch milliseconds (INTEGER) in
 * the DB and in all of these interfaces.
 */

import type { MetaStore } from '../meta/index.js'

/**
 * `ActorRef` (frozen `common.schema.json#/$defs/actorRef`) in its JSON
 * carrier form. The store treats `actor`/`source`/`payload` as opaque JSON:
 * deep validation (INV-HIST-4, the emitter matrix) is the WP-2.2 seam.
 */
export interface ActorRefJson {
  readonly kind: string
  readonly user_id?: string
  readonly run_id?: string
  readonly session_id?: string
  readonly label?: string
}

/**
 * `SourceRef` (frozen `common.schema.json#/$defs/sourceRef`) in its JSON
 * carrier form.
 */
export interface SourceRefJson {
  readonly kind: string
  readonly session_id?: string
  readonly path?: string
  readonly commit_oid?: string
  readonly interaction_id?: string
  readonly note?: string
}

/**
 * An event as accepted by `appendEvents` — the frozen envelope
 * (HISTORY_EVENT_CATALOG §1) MINUS the two store-owned fields:
 *
 *   - `eventSeq` — assigned by the store INSIDE the write transaction
 *     (per owner workstream: `MAX(event_seq) + 1`, TC-HIST-003);
 *   - `recordedAt` — generated by the plugin at write time; 「recordedAt
 *     由插件写入时生成，不接受调用方指定」(HISTORY_EVENT_CATALOG §1 L33).
 *
 * Supplying either field in the input is rejected (`STORE_INPUT`).
 */
export interface HistoryEventInput {
  /** `"H-<n>"`; unique within the Project (PK; §15). Allocated by the
   *  caller via the shared `IdAllocator` (meta counter `HISTORY_EVENT`). */
  readonly eventId: string
  /** The event's single owner workstream (INV-HIST-3). */
  readonly ownerWorkstreamId: string
  /** Event type name from the frozen catalog (HISTORY_EVENT_CATALOG §4). */
  readonly eventType: string
  /** Payload schema version (V1: 1). */
  readonly schemaVersion: number
  /** Reality time of the research event, epoch ms. May predate earlier
   *  events (late registration — seq still takes MAX+1, §1 L32). */
  readonly occurredAt: number
  readonly actor: ActorRefJson
  readonly source?: SourceRefJson | null
  /** Strongly-typed payload (validated by the WP-2.2 hook, not here). */
  readonly payload: Record<string, unknown>
}

/** A fully persisted event — the frozen envelope, camelCase. */
export interface HistoryEventRecord extends HistoryEventInput {
  readonly eventSeq: number
  readonly recordedAt: number
}

/**
 * One `derived_state` row patch (§15 L627: PK `(object_kind, object_id)`,
 * `state` is JSON and replaced wholesale — no merging). Written in the same
 * transaction as the event append it accompanies.
 */
export interface DerivedStatePatch {
  /** Object kind (e.g. `workstream`, `task`, `gate`, `milestone`). */
  readonly objectKind: string
  readonly objectId: string
  /** New state document; JSON-serializable. */
  readonly state: unknown
}

/**
 * Transaction-scoped derived-state face handed to the hooks. Reads observe
 * the state visible at transaction start (pre-batch) so the WP-2.2 mutation
 * check (INV-HIST-5: `from` == current derived state) sees the authoritative
 * pre-append value; writes take effect on COMMIT and roll back on ANY
 * failure of the batch (hook throw included).
 */
export interface TxScope {
  /** Current state JSON for (kind, id), or `null` when never written. */
  getDerivedState(objectKind: string, objectId: string): unknown | null
  /** Replace the whole state JSON for (kind, id). */
  setDerivedState(objectKind: string, objectId: string, state: unknown): void
}

/**
 * TC-DOM-033 context: `workstreamId`'s FIRST event (the log was empty for
 * that workstream before this batch) is being appended in this batch. The
 * callback performs the declarative half of the PLANNED→REALIZED flip
 * (`workstream.yaml` lifecycle via the service's atomic file write) and/or
 * the workstream-lifecycle `derived_state` write via `tx` — with the same
 * transaction semantics as the event row: any throw rolls back EVERYTHING
 * (event row + derived_state + any file-side effect the callback must then
 * undo; the DB half is atomic on its own).
 */
export interface RealizeContext {
  readonly workstreamId: string
  /** The first event for this workstream, with assigned `eventSeq`. */
  readonly event: HistoryEventRecord
  readonly tx: TxScope
}

/**
 * The PLANNED→REALIZED atomic-realize seam (TC-DOM-033 persistence half).
 * The STORE does not know lifecycle (declarative 真源); the caller lists
 * which of the batch's owner workstreams are PLANNED, and the store invokes
 * `apply` — inside the same write transaction, before commit — exactly once
 * per such workstream whose FIRST event is in this batch (in batch order).
 * A workstream already having events, or not in the batch, never triggers.
 */
export interface RealizeHooks {
  /** Owner workstreams that are PLANNED and must flip to REALIZED. */
  readonly workstreamIds: readonly string[]
  /** Invoked within the write transaction. Throw → full batch rollback. */
  readonly apply: (context: RealizeContext) => void
}

export interface AppendEventsOptions {
  /**
   * `derived_state` rows upserted in the same transaction as the events
   * (§15 L627: 「与事件 append 同事务写入」). Order-preserving: later
   * patches for the same (kind, id) win.
   */
  readonly derivedState?: readonly DerivedStatePatch[]
  /**
   * WP-2.2 seam: event validation (payload schema strictness INV-HIST-4,
   * reference existence, mutation `from`-check INV-HIST-5, emitter matrix).
   * Called inside the write transaction after seq assignment and BEFORE any
   * write; reads go through `tx`. The batch's finalized events (with
   * assigned `eventSeq`) are passed in. Throw → the WHOLE batch rolls back
   * and the thrown value propagates to the caller unchanged.
   */
  readonly validate?: (
    events: readonly HistoryEventRecord[],
    tx: TxScope,
  ) => void
  /** See {@link RealizeHooks}. */
  readonly realize?: RealizeHooks
}

export interface AppendResult {
  /** The batch with store-assigned `eventSeq`/`recordedAt`, input order. */
  readonly events: readonly HistoryEventRecord[]
  /** Last assigned seq per affected owner workstream. */
  readonly lastSeqByWorkstream: Readonly<Record<string, number>>
}

/**
 * The operational store handle. APPEND-ONLY surface (INV-HIST-1): this
 * interface has no update/delete/rewrite method — the event log cannot be
 * mutated through the store, and the storage layer rejects raw UPDATE/
 * DELETE on `history_event` via triggers (schema.ts). `derived_state` is a
 * REBUILDABLE cache (TC-HIST-006) and may be replaced wholesale; it is not
 * first-class identity (INV-HIST-7).
 *
 * The query face is deliberately minimal (WP-2.3 owns full
 * replay/projections): `getEvent` + `listRange` only.
 */
export interface ResearchStore {
  /** Absolute path of the SQLite file. */
  readonly path: string
  /** DB schema version this store opened (V1: 1). */
  readonly userVersion: number
  /** Close the connection. Idempotent (safe as an effect disposer). */
  close(): void
  /**
   * Atomically append a batch of events — ONE write transaction, in order:
   * ① seq assignment (per owner WS, MAX+1) → ② `validate` hook → ③ event
   * rows → ④ `derivedState` patches → ⑤ `realize` hooks (first events) →
   * COMMIT. ANY failure (hook throw, constraint violation, SQL error)
   * rolls the ENTIRE batch back — no partial state, no consumed seq
   * (TC-HIST-003 / TC-DOM-033 persistence half).
   */
  appendEvents(
    events: readonly HistoryEventInput[],
    options?: AppendEventsOptions,
  ): AppendResult
  /** Read one event by (owner workstream, seq); `null` when absent. */
  getEvent(ownerWorkstreamId: string, seq: number): HistoryEventRecord | null
  /**
   * Events of one workstream with `eventSeq` in `[fromSeq, toSeq]`
   * (unbounded when `toSeq` omitted), in audit order (`event_seq`).
   */
  listRange(
    ownerWorkstreamId: string,
    fromSeq: number,
    toSeq?: number,
  ): readonly HistoryEventRecord[]
  /**
   * The §15 `meta` table as a WP-1.6 `MetaStore` (same surface, same
   * `id-counter:*` key namespace as the memory backend; `bumpCounter` is
   * one atomic SQL statement — the `IdCounterPort` seam).
   */
  meta(): MetaStore
}
